version: '3.4'

services:
  orderapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3001:3001

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"