version: '3.4'

services:

  reverseproxy:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    depends_on: 
      - orderapi
    ports: 
      - "9090:80"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    container_name: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123"
      RABBITMQ_DEFAULT_VHOST: "/"
    expose:
      - "5672"
      - "15672"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    healthcheck:
      test: ["CMD-SHELL", "if rabbitmqctl status; then \nexit 0 \nfi \nexit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  orderapi:
    build:
      context: https://github.com/bburaksseyhan/order-api.git#main
    restart: on-failure
    links:
      - rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
  
  orderapiconsumer:
      build:
        context: https://github.com/bburaksseyhan/order-api-consumer.git#main
      restart: always
      links:
        - rabbitmq
      depends_on:
        rabbitmq:
          condition: service_healthy
      environment:
        - GO_RABBITMQ_URL=amqp://admin:123@rabbitmq:5672/
